repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check .
        language: python
        types: [python]
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: python
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: python
        types: [python]
        pass_filenames: false
