name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13.5"
      - uses: astral-sh/setup-uv@v1
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock
      - name: Install dependencies
        run: uv sync --extra dev
      - name: Lint with ruff
        run: uv run ruff check .
      - name: Typecheck with mypy
        run: uv run mypy
      - name: Test with pytest
        run: uv run pytest
